### ISSUE TITLE
Carpeta docs

### ISSUE THREAD

**Issue by LicFuraca** [JoyTabellaAlkm/wave27-practicas#1]
Hola @JoyTabellaAlkm !
Quería preguntarte por la carpeta "docs". ¿se supone que ahí iría las exportaciones de postman que hagamos?

Lean nos dijo que lo coloquemos en resources dentro de src.

**Comment by JoyTabellaAlkm** [comment]
Buenas Martín! 
Como dice Lean, las colecciones postman van en la carpeta /src/resources
